// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPF_Proj1;

#nullable disable

namespace WPF_Proj1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308113921_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("WPF_Proj1.DailyMenu", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("TEXT");

                    b.Property<string>("DishA")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("dish_a");

                    b.Property<string>("DishB")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("dish_b");

                    b.Property<string>("Soup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Day");

                    b.ToTable("daily_menu", (string)null);
                });

            modelBuilder.Entity("WPF_Proj1.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("TEXT");

                    b.Property<string>("DishChoice")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("dish_choice");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<bool>("WantsSoup")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wants_soup");

                    b.HasKey("Id");

                    b.HasIndex("Day");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("WPF_Proj1.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WPF_Proj1.Order", b =>
                {
                    b.HasOne("WPF_Proj1.DailyMenu", "DailyMenu")
                        .WithMany("Orders")
                        .HasForeignKey("Day")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WPF_Proj1.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyMenu");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WPF_Proj1.DailyMenu", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WPF_Proj1.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
